### ISSUE TITLE
Improvement: Consider deprecating PageFactory for Page Object Model

### ISSUE THREAD

**Issue by rcooper85** [eliasnogueira/selenium-java-lean-test-achitecture#12]
It is worth considering to remove the use of the PageFactory class in your POM implementation. This has already been deprecated in the .NET version of selenium and it wouldn't surprise me if it was deprecated from the Java version soon. Simon Stewart has admitted on many talks/blogs that PageFactory is really badly implemented. Take a look here (at 27:25)
https://youtu.be/gyfUpOysIF8

**Comment by eliasnogueira** [comment]
Hello Ross,
Thanks to spend you time giving this heads up!
I’m aware of your concern but, at least for Java, it works the use to remove the amount of boilplate in the code.

.Net library has deprecated it because of a technical issue with proxies in the code library. More details here https://github.com/SeleniumHQ/selenium/issues/4387

The solution to replace the page factory is return back to the “old way” of the page object creation.
I can say from my experience that Page Factory approach works for me 100% without any specific waiting issue.
